# Generated by Django 3.0.8 on 2020-07-15 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zcategory',
            options={'verbose_name': '书籍分类', 'verbose_name_plural': '书籍分类'},
        ),
        migrations.AddField(
            model_name='zcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='books.Category', verbose_name='书籍系列'),
        ),
    ]
