# Generated by Django 3.0.8 on 2020-07-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200715_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='书籍封面'),
        ),
    ]
