# Generated by Django 3.0.8 on 2020-07-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='图片链接'),
        ),
    ]
